const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');

console.log('🔄 Configuration pour SQLite...\n');

// 1. Modifier schema.prisma
const schemaPath = path.join(__dirname, '..', 'prisma', 'schema.prisma');
let schemaContent = fs.readFileSync(schemaPath, 'utf8');

// Remplacer MySQL par SQLite
schemaContent = schemaContent.replace(
  /datasource db \{[^}]+\}/s,
  `datasource db {
  provider = "sqlite"
  url      = env("DATABASE_URL")
}`
);

// Décommenter SQLite si présent
schemaContent = schemaContent.replace(
  /\/\/ datasource db \{[\s\S]*?provider = "sqlite"[\s\S]*?\}/,
  `datasource db {
  provider = "sqlite"
  url      = env("DATABASE_URL")
}`
);

// Commenter MySQL si présent
schemaContent = schemaContent.replace(
  /datasource db \{[\s\S]*?provider = "mysql"[\s\S]*?\}/,
  `// datasource db {
//   provider = "mysql"
//   url      = env("DATABASE_URL")
// }`
);

fs.writeFileSync(schemaPath, schemaContent);
console.log('✅ schema.prisma modifié pour SQLite');

// 2. Créer/modifier .env
const envPath = path.join(__dirname, '..', '.env');
let envContent = '';

if (fs.existsSync(envPath)) {
  envContent = fs.readFileSync(envPath, 'utf8');
  // Remplacer DATABASE_URL si présent
  if (envContent.includes('DATABASE_URL=')) {
    envContent = envContent.replace(
      /DATABASE_URL=.*/,
      'DATABASE_URL="file:./prisma/dev.db"'
    );
  } else {
    envContent += '\nDATABASE_URL="file:./prisma/dev.db"';
  }
} else {
  envContent = `DATABASE_URL="file:./prisma/dev.db"
PORT=3001
NODE_ENV=development`;
}

fs.writeFileSync(envPath, envContent);
console.log('✅ Fichier .env configuré');

// 3. Supprimer les migrations MySQL existantes
const migrationsPath = path.join(__dirname, '..', 'prisma', 'migrations');
if (fs.existsSync(migrationsPath)) {
  console.log('\n⚠️  Suppression des migrations MySQL existantes...');
  fs.rmSync(migrationsPath, { recursive: true, force: true });
  console.log('✅ Migrations supprimées');
}

// 4. Mettre à jour migration_lock.toml
const lockPath = path.join(__dirname, '..', 'prisma', 'migrations', 'migration_lock.toml');
const lockDir = path.dirname(lockPath);
if (!fs.existsSync(lockDir)) {
  fs.mkdirSync(lockDir, { recursive: true });
}
fs.writeFileSync(lockPath, `# Please do not edit this file manually
# It should be added in your version-control system (i.e. Git)
provider = "sqlite"
`);
console.log('✅ migration_lock.toml configuré pour SQLite');

console.log('\n📋 Étapes suivantes :');
console.log('1. npm run prisma:generate');
console.log('2. npx prisma migrate dev --name init');
console.log('3. npm run dev');
console.log('\n✨ Configuration SQLite terminée !');
